#pragma once
#include <memory>
#include <dxgi1_4.h>

struct __declspec(uuid("55f734c5-3427-4c7e-85ed-997e11feb216")) DXGISwapChain;
struct D3D11Device;

struct DXGISwapChainHook {
	DXGISwapChainHook() = default;
	virtual ~DXGISwapChainHook();
	DXGISwapChainHook(const DXGISwapChainHook &) = delete;
	DXGISwapChainHook &operator=(const DXGISwapChainHook &) = delete;
	IDXGISwapChain *s_ = nullptr;
	unsigned int version_ = 0;

	/**** Autogenerated hook header ****/
	virtual HRESULT Present(UINT SyncInterval, UINT Flags);
	virtual HRESULT GetBuffer(UINT Buffer, REFIID riid, void **ppSurface);
	virtual HRESULT SetFullscreenState(BOOL Fullscreen, IDXGIOutput *pTarget);
	virtual HRESULT GetFullscreenState(BOOL *pFullscreen, IDXGIOutput **ppTarget);
	virtual HRESULT GetDesc(DXGI_SWAP_CHAIN_DESC *pDesc);
	virtual HRESULT ResizeBuffers(UINT BufferCount, UINT Width, UINT Height, DXGI_FORMAT NewFormat, UINT SwapChainFlags);
	virtual HRESULT ResizeTarget(const DXGI_MODE_DESC *pNewTargetParameters);
	virtual HRESULT GetContainingOutput(IDXGIOutput **ppOutput);
	virtual HRESULT GetFrameStatistics(DXGI_FRAME_STATISTICS *pStats);
	virtual HRESULT GetLastPresentCount(UINT *pLastPresentCount);
	virtual HRESULT GetDesc1(DXGI_SWAP_CHAIN_DESC1 *pDesc);
	virtual HRESULT GetFullscreenDesc(DXGI_SWAP_CHAIN_FULLSCREEN_DESC *pDesc);
	virtual HRESULT GetHwnd(HWND *pHwnd);
	virtual HRESULT GetCoreWindow(REFIID refiid, void **ppUnk);
	virtual HRESULT Present1(UINT SyncInterval, UINT PresentFlags, const DXGI_PRESENT_PARAMETERS *pPresentParameters);
	virtual BOOL IsTemporaryMonoSupported();
	virtual HRESULT GetRestrictToOutput(IDXGIOutput **ppRestrictToOutput);
	virtual HRESULT SetBackgroundColor(const DXGI_RGBA *pColor);
	virtual HRESULT GetBackgroundColor(DXGI_RGBA *pColor);
	virtual HRESULT SetRotation(DXGI_MODE_ROTATION Rotation);
	virtual HRESULT GetRotation(DXGI_MODE_ROTATION *pRotation);
	virtual HRESULT SetSourceSize(UINT Width, UINT Height);
	virtual HRESULT GetSourceSize(UINT *pWidth, UINT *pHeight);
	virtual HRESULT SetMaximumFrameLatency(UINT MaxLatency);
	virtual HRESULT GetMaximumFrameLatency(UINT *pMaxLatency);
	virtual HANDLE GetFrameLatencyWaitableObject();
	virtual HRESULT SetMatrixTransform(const DXGI_MATRIX_3X2_F *pMatrix);
	virtual HRESULT GetMatrixTransform(DXGI_MATRIX_3X2_F *pMatrix);
	virtual UINT GetCurrentBackBufferIndex();
	virtual HRESULT CheckColorSpaceSupport(DXGI_COLOR_SPACE_TYPE ColorSpace, UINT *pColorSpaceSupport);
	virtual HRESULT SetColorSpace1(DXGI_COLOR_SPACE_TYPE ColorSpace);
	virtual HRESULT ResizeBuffers1(UINT BufferCount, UINT Width, UINT Height, DXGI_FORMAT Format, UINT SwapChainFlags, const UINT *pCreationNodeMask, IUnknown *const *ppPresentQueue);
	/**** End autogenerated hook header ****/
};

struct DXGISwapChain : IDXGISwapChain3 {
	LONG ref_ = 1;
	IDXGISwapChain *s_;
	unsigned int version_;
	D3D11Device *const device_;
	std::shared_ptr<DXGISwapChainHook> h_;

	void updateHook();
	DXGISwapChain(D3D11Device *device, IDXGISwapChain *original, std::shared_ptr<DXGISwapChainHook> hook);
	DXGISwapChain(D3D11Device *device, IDXGISwapChain1 *original, std::shared_ptr<DXGISwapChainHook> hook);

	DXGISwapChain(const DXGISwapChain &) = delete;
	DXGISwapChain &operator=(const DXGISwapChain &) = delete;

#pragma region IUnknown
	virtual HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void **ppvObj) override;
	virtual ULONG STDMETHODCALLTYPE AddRef() override;
	virtual ULONG STDMETHODCALLTYPE Release() override;
#pragma endregion
#pragma region IDXGIObject
	virtual HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID Name, UINT DataSize, const void *pData) override;
	virtual HRESULT STDMETHODCALLTYPE SetPrivateDataInterface(REFGUID Name, const IUnknown *pUnknown) override;
	virtual HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID Name, UINT *pDataSize, void *pData) override;
	virtual HRESULT STDMETHODCALLTYPE GetParent(REFIID riid, void **ppParent) override;
#pragma endregion
#pragma region IDXGIDeviceSubObject
	virtual HRESULT STDMETHODCALLTYPE GetDevice(REFIID riid, void **ppDevice) override;
#pragma endregion
#pragma region IDXGISwapChain
	virtual HRESULT STDMETHODCALLTYPE Present(UINT SyncInterval, UINT Flags) override;
	virtual HRESULT STDMETHODCALLTYPE GetBuffer(UINT Buffer, REFIID riid, void **ppSurface) override;
	virtual HRESULT STDMETHODCALLTYPE SetFullscreenState(BOOL Fullscreen, IDXGIOutput *pTarget) override;
	virtual HRESULT STDMETHODCALLTYPE GetFullscreenState(BOOL *pFullscreen, IDXGIOutput **ppTarget) override;
	virtual HRESULT STDMETHODCALLTYPE GetDesc(DXGI_SWAP_CHAIN_DESC *pDesc) override;
	virtual HRESULT STDMETHODCALLTYPE ResizeBuffers(UINT BufferCount, UINT Width, UINT Height, DXGI_FORMAT NewFormat, UINT SwapChainFlags) override;
	virtual HRESULT STDMETHODCALLTYPE ResizeTarget(const DXGI_MODE_DESC *pNewTargetParameters) override;
	virtual HRESULT STDMETHODCALLTYPE GetContainingOutput(IDXGIOutput **ppOutput) override;
	virtual HRESULT STDMETHODCALLTYPE GetFrameStatistics(DXGI_FRAME_STATISTICS *pStats) override;
	virtual HRESULT STDMETHODCALLTYPE GetLastPresentCount(UINT *pLastPresentCount) override;
#pragma endregion
#pragma region IDXGISwapChain1
	virtual HRESULT STDMETHODCALLTYPE GetDesc1(DXGI_SWAP_CHAIN_DESC1 *pDesc) override;
	virtual HRESULT STDMETHODCALLTYPE GetFullscreenDesc(DXGI_SWAP_CHAIN_FULLSCREEN_DESC *pDesc) override;
	virtual HRESULT STDMETHODCALLTYPE GetHwnd(HWND *pHwnd) override;
	virtual HRESULT STDMETHODCALLTYPE GetCoreWindow(REFIID refiid, void **ppUnk) override;
	virtual HRESULT STDMETHODCALLTYPE Present1(UINT SyncInterval, UINT PresentFlags, const DXGI_PRESENT_PARAMETERS *pPresentParameters) override;
	virtual BOOL STDMETHODCALLTYPE IsTemporaryMonoSupported() override;
	virtual HRESULT STDMETHODCALLTYPE GetRestrictToOutput(IDXGIOutput **ppRestrictToOutput) override;
	virtual HRESULT STDMETHODCALLTYPE SetBackgroundColor(const DXGI_RGBA *pColor) override;
	virtual HRESULT STDMETHODCALLTYPE GetBackgroundColor(DXGI_RGBA *pColor) override;
	virtual HRESULT STDMETHODCALLTYPE SetRotation(DXGI_MODE_ROTATION Rotation) override;
	virtual HRESULT STDMETHODCALLTYPE GetRotation(DXGI_MODE_ROTATION *pRotation) override;
#pragma endregion
#pragma region IDXGISwapChain2
	virtual HRESULT STDMETHODCALLTYPE SetSourceSize(UINT Width, UINT Height) override;
	virtual HRESULT STDMETHODCALLTYPE GetSourceSize(UINT *pWidth, UINT *pHeight) override;
	virtual HRESULT STDMETHODCALLTYPE SetMaximumFrameLatency(UINT MaxLatency) override;
	virtual HRESULT STDMETHODCALLTYPE GetMaximumFrameLatency(UINT *pMaxLatency) override;
	virtual HANDLE STDMETHODCALLTYPE GetFrameLatencyWaitableObject() override;
	virtual HRESULT STDMETHODCALLTYPE SetMatrixTransform(const DXGI_MATRIX_3X2_F *pMatrix) override;
	virtual HRESULT STDMETHODCALLTYPE GetMatrixTransform(DXGI_MATRIX_3X2_F *pMatrix) override;
#pragma endregion
#pragma region IDXGISwapChain3
	virtual UINT STDMETHODCALLTYPE GetCurrentBackBufferIndex() override;
	virtual HRESULT STDMETHODCALLTYPE CheckColorSpaceSupport(DXGI_COLOR_SPACE_TYPE ColorSpace, UINT *pColorSpaceSupport) override;
	virtual HRESULT STDMETHODCALLTYPE SetColorSpace1(DXGI_COLOR_SPACE_TYPE ColorSpace) override;
	virtual HRESULT STDMETHODCALLTYPE ResizeBuffers1(UINT BufferCount, UINT Width, UINT Height, DXGI_FORMAT Format, UINT SwapChainFlags, const UINT *pCreationNodeMask, IUnknown *const *ppPresentQueue) override;
#pragma endregion
};
